### ISSUE TITLE
Questions about upgrading to substrate3.0

### ISSUE THREAD

**Issue by 99Kies** [zhangjiannan/QFgrant#3]
Is there any upgrade plan now? I am trying to upgrade to substrate3.0, but I encountered a lot of problems during the upgrade process.

**Comment by 99Kies** [comment]
<https://github.com/99Kies/QFgrant>

**Comment by tinydjp** [comment]
Hi @99Kies did u finish  the upgrade? As we're busy with build our own node, hope it's not too late. The QF pallet has integrated with our own node, you can check here https://github.com/DoraFactory/dorafactory-node/tree/dora-grant. It's substrate 3.0 version

**Comment by 99Kies** [comment]
@tinydjp I am sorry that I am a little busy these days. I have temporarily suspended the upgrade. I would like to ask whether this part has been upgraded?

**Comment by 99Kies** [comment]
@tinydjp Is this warehouse not maintained now?

**Comment by tinydjp** [comment]
not maintained, we've moved to DoraFactory, it's open source too.

**Comment by 99Kies** [comment]
> not maintained, we've moved to DoraFactory, it's open source too.

https://github.com/DoraFactory/dorafactory-node/pull/2
